server.host=0.0.0.0
server.port=12345

chat.max-message-length=1000
chat.max-client-name-length=20
chat.max-connections=10
chat.max-history-length=100
chat.authentication-timeout=20000

rate-limit.max-connections=5
rate-limit.duration-ms=10000